### ISSUE TITLE
Modular base paths in config

### ISSUE THREAD

**Issue by charles-zhng** [talmolab/track-mjx#57]
Currently we assume the base path is our current working directory, but we should have (optional?) user-defined base paths for various inputs and outputs we need to read/write. Minimally, we should have a base path for:
- data (stac'd data)
- outputs (checkpoints and wandb logs)

we can make a new config directory called `paths` in which to store the yaml file which can look like:
```yaml
user: charleszhang
data_dir: .../lab/data/track-mjx
outputs: .../lab/User/${paths.user}/track-mjx
```
